# Generated by Django 5.0.7 on 2024-08-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0007_alter_sharedfile_role'),
        ('folder_management', '0005_sharedfolder_role_alter_sharedfolder_folder'),
        ('user_management', '0003_alter_customuser_id_alter_friendrequest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='starred_files',
            field=models.ManyToManyField(blank=True, to='file_management.file'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='starred_folders',
            field=models.ManyToManyField(blank=True, to='folder_management.folder'),
        ),
    ]
