# Generated by Django 5.0.7 on 2024-08-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_customuser_starred_files_customuser_starred_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='used_space',
            field=models.BigIntegerField(default=0),
        ),
    ]
