# Generated by Django 5.0.7 on 2024-10-01 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('access_everyone', models.BooleanField(default=False)),
                ('access_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starred', models.BooleanField(default=False)),
                ('binned', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='folder_management.folder')),
            ],
        ),
        migrations.CreateModel(
            name='SharedFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[(1, 'Viewer'), (2, 'Commentor'), (3, 'Editor')], default=1, max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_management.folder')),
            ],
        ),
    ]
