# Generated by Django 5.0.7 on 2024-08-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='binned',
            field=models.DateTimeField(null=True),
        ),
    ]
