# Generated by Django 5.0.7 on 2024-08-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_management', '0003_sharedfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='binned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
