# Generated by Django 5.0.7 on 2024-08-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_management', '0005_sharedfolder_role_alter_sharedfolder_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfolder',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sharedfolder',
            name='role',
            field=models.CharField(choices=[(1, 'Viewer'), (2, 'Commentor'), (3, 'Editor')], default=1, max_length=255),
        ),
    ]
