# Generated by Django 5.0.7 on 2024-10-01 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to='temp/')),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField()),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_everyone', models.BooleanField(default=False)),
                ('access_count', models.IntegerField(default=0)),
                ('starred', models.BooleanField(default=False)),
                ('binned', models.DateTimeField(blank=True, null=True)),
                ('thumbnail', models.ImageField(default='thumbnail.png', upload_to='temp/')),
            ],
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[(1, 'Viewer'), (2, 'Editor'), (3, 'Commentor')], default=1, max_length=255)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
