# Generated by Django 5.0.7 on 2024-08-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='binned',
            field=models.DateTimeField(null=True),
        ),
    ]
