# Generated by Django 5.0.7 on 2024-10-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_alter_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
