# Generated by Django 5.0.7 on 2024-08-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_sharedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='binned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
