# Generated by Django 5.0.7 on 2024-08-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0004_alter_file_binned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.PositiveBigIntegerField(),
        ),
    ]
