# Generated by Django 5.0.7 on 2024-08-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0005_alter_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='role',
            field=models.CharField(choices=[(1, 'Viewer'), (2, 'Editor'), (3, 'Commentor'), (4, 'Administrator')], default=1, max_length=255),
        ),
    ]
