# Generated by Django 5.0.7 on 2024-08-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0006_sharedfile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='role',
            field=models.CharField(choices=[(1, 'Viewer'), (2, 'Editor'), (3, 'Commentor'), (4, 'Administrator'), (5, 'Uploader')], default=1, max_length=255),
        ),
    ]
