# Generated by Django 5.0.7 on 2024-08-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0007_alter_sharedfile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='role',
            field=models.CharField(choices=[(1, 'Viewer'), (2, 'Editor'), (3, 'Commentor')], default=1, max_length=255),
        ),
    ]
