# Generated by Django 5.0.7 on 2024-09-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0008_sharedfile_visible_alter_sharedfile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(default='thumbnail.png', upload_to='temp/'),
        ),
    ]
